version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - app_network

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: Development
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: test_dbo
    ports:
      - "5433:5432"
    networks:
      - app_network
    volumes:
    - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Development -d test_dbo"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  postgres_data:

networks:
  app_network:
